# encoding:utf-8
# print(type("哈哈"))
# print(type(2333))
# print(type(2.333))
# print(type(True))
# print(type(()))
# print(type([]))
# print(type({}))
# a = int("2333")
# print(type(a))
# a = "哈哈"
# print(len(a))
a = input("请输入：")
b = input("请输入：")
print("input获取的内容:",len(a+b))